### PR TITLE
enable ppc64le and aarch64

### LINKED ISSUE #27: Can you add support to arch linux-aarch64
### Comment:

Our [aiidalab docker](https://github.com/aiidalab/aiidalab-docker-stack/blob/develop/Dockerfile) has dependent on `openbabel` and install it from this conda. We now provide docker support for aarch64 architecture but stuck in `conda install -c conda-forge openbabel`.

### PR DESCRIPTION
**Pull request by njzjz**
Based on #26. Fix #27.

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin  rerender

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by unkcpz** [comment]
@njzjz Thanks a lot! I am not expert on conda-forge, so I only review your additional commits. It looks all good and seems the aarch64 forge is generated.
Cheers!

**Pull request merged**
