### PR TITLE
Rebuild with new compilers

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
It seems like `openbabel` fails with the new compiler versions, which is presumably also the reason why https://github.com/conda-forge/openbabel-feedstock/pull/35 fails.

**Comment by njzjz** [comment]
We need a patch. Adding `#include <ctime>` should fix all errors.

**Comment by jan-janssen** [comment]
> We need a patch. Adding `#include <ctime>` should fix all errors.

Thanks - that seems to work.

**Comment by jan-janssen** [comment]
@njzjz The tests passed successful, so from my perspective the pull request is ready to be merged.

**Review by njzjz — APPROVED** [review]
Approve - but I think we should wait until https://github.com/conda-forge/status/issues/144 is fixed.

**Pull request merged**
