### PR TITLE
Fix for Windows build and InChI in Windows build

### PR DESCRIPTION
**Pull request by fredrikw**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Two sets of small fixes to get Windows builds to work.
1. I fixed compilation on Appveyor by adding `#include <iterator>` to obmolecformat.cpp (see https://github.com/erengy/anitomy/issues/2) and removing Boost.
   Removing Boost unfortunately means that the Maestro format won't build, but I got some strange linking errors that will require some more debugging.
2. Set OB_USE_PREBUILT_BINARIES to OFF to make sure that libinchi is compiled.

I forgot to bump the build number...

### CODE REVIEW

**Comment by mcs07** [comment]
I have a version of this recipe that works on Azure pipelines at https://github.com/mcs07/conda-recipes/tree/master/recipes/openbabel

I was waiting on https://github.com/conda-forge/inchi-feedstock/pull/2 to be merged so we can the latest InChI version instead of the old bundled version, but it might be quicker to just go with the bundled one like you have done.

**Comment by mcs07** [comment]
`-D WITH_MAEPARSER=OFF` in bld.bat might do the job. Looks like cmake is still trying to build maeparser even though boost isn't present.

**Comment by fredrikw** [comment]
Yes, there seems to be a difference between Appveyor and Azure Pipelines in how they treat Boost. Appveyor works when Boost is not added but Azure Pipelines seems to find a version but not enough for maeparser to build... But it might be better to use WITH_MAEPARSER=OFF as well. I'll add it so we can see.

**Comment by mcs07** [comment]
Hopefully that should work. I didn't actually realise we can stick with Appveyor if needed (https://github.com/conda-forge/conda-forge.github.io/issues/857) - in which case I guess we just ignore the failing azure builds and merge this. But if Azure works, it would be good to standardise on that. If so, I think we also need to remove the 2 lines added in this commit https://github.com/conda-forge/openbabel-feedstock/commit/b6775fbde257929802959a95c8aa334650ef2507 and re-render to remove the Appveyor CI.

**Comment by fredrikw** [comment]
Now all checks passed. I still forgot to update the build number though...

**Comment by fredrikw** [comment]
Would you like me to update build number and switch to Azure-only on this PR?

**Comment by mcs07** [comment]
There are also a couple of other changes I'd like to make, I'll try push them onto your branch so we can do it all in one go.

**Comment by mcs07** [comment]
@conda-forge-admin, please rerender

**Comment by mcs07** [comment]
@njzjz Can you remember why `CMAKE_SHARED_LINKER_FLAGS_INIT='-pthread -lrt -lutil'` was added for linux? I just removed it when tidying up `build.sh` but I can put it back if is actually needed.

**Comment by njzjz** [comment]
> @njzjz Can you remember why `CMAKE_SHARED_LINKER_FLAGS_INIT='-pthread -lrt -lutil'` was added for linux? I just removed it when tidying up `build.sh` but I can put it back if is actually needed.

It fixed `undefined reference` (I think it was a bug of `ln`). It can be removed if this bug has been fixed.

**Comment by mcs07** [comment]
Ah, here is the failing linux build with `undefined reference` errors from before that was added: https://circleci.com/gh/conda-forge/staged-recipes/34720 

But now everything seems fine without it, so I will leave it out.

@fredrikw Are you OK with my additional changes?

**Comment by mcs07** [comment]
@conda-forge-admin, please rerender

**Comment by mcs07** [comment]
I thought the Appveyor CI check would disappear once the rerender deleted `.appveyor.yml`, but it seems to be running and failing because there is nothing to run. I guess it is harmless, and might disappear in future PRs once this one is merged...

**Comment by fredrikw** [comment]
Looks good to me. I also had plans to look at the "Remove run requirements that have run_exports"...

Just FYI, I noticed while working that obabel now actually fails when it cannot convert a molecule. (see https://ci.appveyor.com/project/fredrikw/openbabel-feedstock/builds/28650035/job/q1grptc94tb5pd4l#L2459). So hopefully, we won't ship a conda build without inchi support again...

**Comment by mcs07** [comment]
@fredrikw Would you like to be added to the maintainers for this feedstock? You'll get notifications about Issues/PRs and the ability to merge PRs.

**Comment by fredrikw** [comment]
@mcs07 Sure, you can add me as a maintainer. Do you have any specific guidelines on reviews and merges?

**Comment by mcs07** [comment]
No specific guidelines that I know of.... Remember to make all changes through PRs from your own fork, even though you can technically push to master and create branches in this repo. Try to get another maintainer to check changes before merging... that's about it.

**Comment by baoilleach** [comment]
Remember to push any relevant fixes for compilation with MSVC2015 upstream. We can maybe also set this as a build target for the main project to ensure that we don't break it.

**Pull request merged**
