### PR TITLE
Fix win datadir

### PR DESCRIPTION
**Pull request by fredrikw**
This is intended to fix the issues that arises due to Conda not able to find the correct BABEL_DATADIR when building on Windows. This is the reason behind https://github.com/openbabel/openbabel/issues/2409 and https://github.com/openbabel/openbabel/issues/2372

I also tried to change the testing to actually fail when tests fail. Since `obabel` exits with 0 also when formats or data files are not found the current tests don't amount to anything. There are optional ways to do this but this was most in line with the current solution I think. An option would be to change the `tests: -> commands`-lines to things like `- python -c "import subprocess;exit(b'1 molecule converted' not in subprocess.run(['obabel', '-:c1ccccc1', '--gen3d', '-oinchi'], capture_output=True).stderr)"` but I thought the way in this PR is more clear.

It's marked as **WIP** since I wanted to get a failing test on the CI before correcting the issue. I also have a question on the best possible solution to set the env correctly that I will expand on below in comments. I will also take care of the build number and re-rendering before removing  **WIP**

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by fredrikw** [comment]
Ok, now there is a fix pushed that fixes all the failing tests. This solution is the simplest one, where we copy a script to set the environment variable on activation of the conda env. According to conda-build docs (https://docs.conda.io/projects/conda-build/en/latest/resources/activate-scripts.html) this is to be avoided when possible but I don't understand the build process well enough to find another solution. It should be possible to update the build files to have the correct hard-coded BABEL_DATADIR (as it does for OSX and Linux) but my efforts in that direction has failed.

I'll leave it like this for a couple of days to see if anyone has a hint as to how we could make a less hacky solution.

**Comment by njzjz** [comment]
@conda-forge-admin please rerender

**Comment by fredrikw** [comment]
With no other input, I went ahead and bumped the build number and removed the WIP-status. I also updated the activation-scripts to stash and reset BABEL_DATADIR if it was set before activation of the conda environment.

To me, this is ready to merge now.

**Comment by mcs07** [comment]
I haven't been able to test locally, but in principle this looks fine to me.

Ideally the hard-coded path detection and prefix replacement in conda-build would mean this isn't necessary... but I don't know enough about it to say whether it is possible to rely on that. Maybe if the `BABEL_DATADIR` environment variable is set at build time it might help?

Also, I take it that there's no need to set `BABEL_LIBDIR` in the same way?

**Comment by fredrikw** [comment]
I also thought the path-detection and prefix replacement would do it, but I couldn't make it work. I managed to get the path updated in the binary files, but there is something in how BABEL_DATADIR works that still made the wrong folder turn up in tokenst.cpp from the makro. Too much c++-makro smartness for my brain...
I haven't noticed a problem with BABEL_LIBDIR, not for myself and not in user reports.

**Review by mcs07 — APPROVED** [review]

**Comment by baoilleach** [comment]
Thanks for all your work here. We really should move away from relying on BABEL_DATADIR to be set. With OB 3.0, I managed to reduce the amount of data read from there but there's still more to go.

**Pull request merged**
